/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.light;
import java.sql.*;
import javax.swing.JOptionPane;
import java.net.*;
import java.awt.Color;
import java.util.Scanner;
import java.io.IOException;
import java.io.PrintStream;
import java.io.FileOutputStream;

/**
 *
 * @author Avi
 */
public class LoginApp extends javax.swing.JFrame {

    /**
     * Creates new form LoginApp
     */
    public LoginApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jRefresh = new javax.swing.JButton();
        jL1_label = new javax.swing.JLabel();
        jL2_label = new javax.swing.JLabel();
        jL4_label = new javax.swing.JLabel();
        jStatus_LB = new javax.swing.JLabel();
        jL1_TF = new javax.swing.JTextField();
        jL2_TF = new javax.swing.JTextField();
        jOnline_TF = new javax.swing.JTextField();
        jOffline_TF = new javax.swing.JTextField();
        jL1_ON = new javax.swing.JButton();
        jL1_OFF = new javax.swing.JButton();
        jL2_ON = new javax.swing.JButton();
        jL2_OFF = new javax.swing.JButton();
        jEXIT2 = new javax.swing.JButton();
        jOnline_LB = new javax.swing.JLabel();
        jOffline_LB = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jL3_label = new javax.swing.JLabel();
        jL3_TF = new javax.swing.JTextField();
        jL4_TF = new javax.swing.JTextField();
        jL3_ON = new javax.swing.JButton();
        jL4_ON = new javax.swing.JButton();
        jL3_OFF = new javax.swing.JButton();
        jL4_OFF = new javax.swing.JButton();
        jL5_LB = new javax.swing.JLabel();
        jL5_TF = new javax.swing.JTextField();
        jL5_ON = new javax.swing.JButton();
        jL5_OFF = new javax.swing.JButton();
        jLoginForm_LB = new javax.swing.JLabel();
        jUN_LB = new javax.swing.JLabel();
        jUsn_TF = new javax.swing.JTextField();
        jPwd_PF = new javax.swing.JPasswordField();
        jPwd_LB = new javax.swing.JLabel();
        jLogin_BT = new javax.swing.JButton();
        jClear1_BT = new javax.swing.JButton();
        jEXIT1_BT = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setTitle("Application");
        jFrame1.setName("Application"); // NOI18N
        jFrame1.setPreferredSize(new java.awt.Dimension(700, 500));
        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRefresh.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jRefresh.setText("Auto Refresh");
        jRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRefreshActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 43, 130, -1));

        jL1_label.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jL1_label.setForeground(new java.awt.Color(51, 51, 51));
        jL1_label.setText("Light-1");
        jFrame1.getContentPane().add(jL1_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 70, 20));

        jL2_label.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jL2_label.setForeground(new java.awt.Color(51, 51, 51));
        jL2_label.setText("Light-2");
        jFrame1.getContentPane().add(jL2_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 70, -1));

        jL4_label.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jL4_label.setForeground(new java.awt.Color(51, 51, 51));
        jL4_label.setText("Light-4");
        jFrame1.getContentPane().add(jL4_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 70, -1));

        jStatus_LB.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jStatus_LB.setText("Status:");
        jFrame1.getContentPane().add(jStatus_LB, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 70, 20));

        jL1_TF.setEditable(false);
        jL1_TF.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jL1_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jL1_TFActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jL1_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 130, -1));

        jL2_TF.setEditable(false);
        jL2_TF.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jL2_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jL2_TFActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jL2_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 130, -1));

        jOnline_TF.setEditable(false);
        jOnline_TF.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jOnline_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOnline_TFActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jOnline_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 50, 23));

        jOffline_TF.setEditable(false);
        jOffline_TF.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jOffline_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOffline_TFActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jOffline_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 50, 23));

        jL1_ON.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jL1_ON.setText("Switch ON?");
        jL1_ON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jL1_ONActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jL1_ON, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 120, -1));

        jL1_OFF.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jL1_OFF.setText("Switch OFF?");
        jL1_OFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jL1_OFFActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jL1_OFF, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 130, -1));

        jL2_ON.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jL2_ON.setText("Switch ON?");
        jL2_ON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jL2_ONActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jL2_ON, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 120, -1));

        jL2_OFF.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jL2_OFF.setText("Switch OFF?");
        jL2_OFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jL2_OFFActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jL2_OFF, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 130, -1));

        jEXIT2.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jEXIT2.setText("Exit");
        jEXIT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEXIT2ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jEXIT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 90, 40));

        jOnline_LB.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jOnline_LB.setText("Online");
        jFrame1.getContentPane().add(jOnline_LB, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 60, -1));

        jOffline_LB.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jOffline_LB.setText("Offline");
        jFrame1.getContentPane().add(jOffline_LB, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 90, 60, -1));

        jLabel10.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Light-2");
        jFrame1.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 70, -1));

        jL3_label.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jL3_label.setForeground(new java.awt.Color(51, 51, 51));
        jL3_label.setText("Light-3");
        jFrame1.getContentPane().add(jL3_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 70, 20));

        jL3_TF.setEditable(false);
        jL3_TF.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jL3_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jL3_TFActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jL3_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 130, -1));

        jL4_TF.setEditable(false);
        jL4_TF.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jL4_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jL4_TFActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jL4_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 130, -1));

        jL3_ON.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jL3_ON.setText("Switch ON?");
        jL3_ON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jL3_ONActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jL3_ON, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 120, -1));

        jL4_ON.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jL4_ON.setText("Switch ON?");
        jL4_ON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jL4_ONActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jL4_ON, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 120, -1));

        jL3_OFF.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jL3_OFF.setText("Switch OFF?");
        jL3_OFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jL3_OFFActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jL3_OFF, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 130, -1));

        jL4_OFF.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jL4_OFF.setText("Switch OFF?");
        jL4_OFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jL4_OFFActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jL4_OFF, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 130, -1));

        jL5_LB.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jL5_LB.setForeground(new java.awt.Color(51, 51, 51));
        jL5_LB.setText("Light-5");
        jFrame1.getContentPane().add(jL5_LB, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 70, -1));

        jL5_TF.setEditable(false);
        jL5_TF.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jL5_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jL5_TFActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jL5_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 130, -1));

        jL5_ON.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jL5_ON.setText("Switch ON?");
        jL5_ON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jL5_ONActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jL5_ON, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 120, -1));

        jL5_OFF.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jL5_OFF.setText("Switch OFF?");
        jL5_OFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jL5_OFFActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jL5_OFF, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 130, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(102, 51, 255));
        setForeground(new java.awt.Color(102, 102, 255));

        jLoginForm_LB.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLoginForm_LB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLoginForm_LB.setText("LOGIN FORM");

        jUN_LB.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jUN_LB.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jUN_LB.setText("User Name");

        jUsn_TF.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jUsn_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsn_TFActionPerformed(evt);
            }
        });

        jPwd_PF.setBackground(new java.awt.Color(153, 255, 0));
        jPwd_PF.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jPwd_PF.setText("");
        jPwd_PF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPwd_PFMouseEntered(evt);
            }
        });
        jPwd_PF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPwd_PFActionPerformed(evt);
            }
        });
        jPwd_PF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPwd_PFKeyReleased(evt);
            }
        });

        jPwd_LB.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jPwd_LB.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPwd_LB.setText("Password");

        jLogin_BT.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLogin_BT.setText("Log In");
        jLogin_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogin_BTActionPerformed(evt);
            }
        });

        jClear1_BT.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jClear1_BT.setText("Clear");
        jClear1_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClear1_BTActionPerformed(evt);
            }
        });

        jEXIT1_BT.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jEXIT1_BT.setText("EXIT");
        jEXIT1_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEXIT1_BTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jUN_LB, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPwd_LB, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLogin_BT, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jClear1_BT)
                                .addGap(34, 34, 34)
                                .addComponent(jEXIT1_BT))
                            .addComponent(jPwd_PF, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jUsn_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLoginForm_LB, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLoginForm_LB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUN_LB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUsn_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPwd_LB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPwd_PF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLogin_BT)
                    .addComponent(jClear1_BT)
                    .addComponent(jEXIT1_BT))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUsn_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsn_TFActionPerformed
        jLogin_BTActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jUsn_TFActionPerformed

    private void jPwd_PFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPwd_PFMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPwd_PFMouseEntered

    private void jPwd_PFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPwd_PFActionPerformed

        jLogin_BTActionPerformed(evt);

        // TODO add your handling code here:
    }//GEN-LAST:event_jPwd_PFActionPerformed

    private void jPwd_PFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPwd_PFKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPwd_PFKeyReleased

    private void jLogin_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogin_BTActionPerformed

        String sql="Select * from login_cred";
    try {
    Class.forName("com.mysql.jdbc.Driver");
    Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/login_database","root","root");
    /*As we are creating a connection on a local computer we will write the url as jdbc:mysql://localhost:3306 */
    Statement stmt=con.createStatement();
    ResultSet rs = stmt.executeQuery(sql);
    String user=jUsn_TF.getText();
    String pwd= new String (jPwd_PF.getPassword());
    int tmp=0;
    while(rs.next())
    {
    String uname=rs.getString("Username");
        //Username is the coloumn name in the database table
    String password=rs.getString("Password");
    if ((user.equals(uname)) && (pwd.equals(password)))
    {
       // javax.swing.JOptionPane.showMessageDialog(jButton1,"Welcome");
        jFrame1.setVisible(true);
        jFrame1.setSize(700, 500);
        jRefreshActionPerformed(evt);
        dispose();
        tmp++;
    }
    }
    if(tmp == 0)
    {
        javax.swing.JOptionPane.showMessageDialog(jLogin_BT,"Enter Correct User Name and password");
    }
    
    //new Home().setVisible(true);
}
    
    catch (Exception e){
    JOptionPane.showMessageDialog(this, e.getMessage());
    }  
        // TODO add your handling code here:
    }//GEN-LAST:event_jLogin_BTActionPerformed

    private void jClear1_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClear1_BTActionPerformed
        jUsn_TF.setText("");
        jPwd_PF.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jClear1_BTActionPerformed

    private void jEXIT1_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEXIT1_BTActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jEXIT1_BTActionPerformed

    private void jRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRefreshActionPerformed
                        jRefresh.setEnabled(false);
                        jL1_ON.setEnabled(false);
                        jL1_OFF.setEnabled(false);
                        jL2_ON.setEnabled(false);
                        jL2_OFF.setEnabled(false);
                        jL3_ON.setEnabled(false);
                        jL3_OFF.setEnabled(false);
                        jL4_ON.setEnabled(false);
                        jL4_OFF.setEnabled(false);
                        jL5_ON.setEnabled(false);
                        jL5_OFF.setEnabled(false);
                        jL1_ON.setText("Switch ON?");
                        jL1_OFF.setText("Switch OFF?");
                        jL2_ON.setText("Switch ON?");
                        jL2_OFF.setText("Switch OFF?");
                        jL3_ON.setText("Switch ON?");
                        jL3_OFF.setText("Switch OFF?");
                        jL4_ON.setText("Switch ON?");
                        jL4_OFF.setText("Switch OFF?");
                        jL5_ON.setText("Switch ON?");
                        jL5_OFF.setText("Switch OFF?");
                        
        Thread refresh =new Thread(){
  public void run(){
      jL1_TF.setBackground(Color.white);
      jL2_TF.setBackground(Color.white);
      jL3_TF.setBackground(Color.white);
      jL4_TF.setBackground(Color.white);
      jL5_TF.setBackground(Color.white);
      
      while(true){
      Socket sock= new Socket();
      InetSocketAddress addr= new InetSocketAddress("www.google.com",80);
      try{
          sock.connect(addr,3000);
          jOnline_TF.setBackground(Color.green);
          jOffline_TF.setBackground(Color.white);
        try 
        {                          
        String[] command = {"cmd.exe", "/C", "Start /b /wait","E:\\iot\\pull.bat"};
        Process p= Runtime.getRuntime().exec(command);
        int exitVal = p.waitFor();        
                          
            java.io.File file = new java.io.File("E:\\iot\\ledread\\log.txt");                     
            Scanner input = new Scanner(file);
             //Thread.sleep(10000);
            while (input.hasNext( ) )
            {       
                jL1_ON.setBackground(Color.green);
                jL1_OFF.setBackground(Color.red);
                jL2_ON.setBackground(Color.green);
                jL2_OFF.setBackground(Color.red);             
                jL3_ON.setBackground(Color.green);
                jL3_OFF.setBackground(Color.red);
                jL4_ON.setBackground(Color.green);
                jL4_OFF.setBackground(Color.red);             
                jL5_ON.setBackground(Color.green);
                jL5_OFF.setBackground(Color.red);             
                
                String num = input.nextLine();
                char charData = num.charAt(0);
                char charData1 = num.charAt(1);               
                char charData2 = num.charAt(2);
                char charData3 = num.charAt(3);               
                char charData4 = num.charAt(4);               
                
                if (charData == '1')  {
                        jL1_TF.setBackground(Color.green);
                        jL1_ON.setEnabled(false);
                        jL1_ON.setText("Switch ON?");
                        jL1_OFF.setEnabled(true); 
                        jL1_OFF.setText("Switch OFF?");
                        
                 }
                else                     {
                        jL1_TF.setBackground(Color.red);
                        jL1_ON.setEnabled(true);
                        jL1_ON.setText("Switch ON?");
                        jL1_OFF.setEnabled(false);
                        jL1_OFF.setText("Switch OFF?");
                }
                if (charData1 == '1')  {
                        jL2_TF.setBackground(Color.green);
                        jL2_ON.setEnabled(false);
                        jL2_ON.setText("Switch ON?");
                        jL2_OFF.setEnabled(true);
                         jL2_OFF.setText("Switch OFF?");
                }
                else                     {
                        jL2_TF.setBackground(Color.red);
                        jL2_ON.setEnabled(true);
                        jL2_ON.setText("Switch ON?");
                        jL2_OFF.setEnabled(false);
                        jL2_OFF.setText("Switch OFF?");
                }
                
                if (charData2 == '1')  {
                        jL3_TF.setBackground(Color.green);
                        jL3_ON.setEnabled(false);
                        jL3_ON.setText("Switch ON?");
                        jL3_OFF.setEnabled(true);
                         jL3_OFF.setText("Switch OFF?");
                }
                else                     {
                        jL3_TF.setBackground(Color.red);
                        jL3_ON.setEnabled(true);
                        jL3_ON.setText("Switch ON?");
                        jL3_OFF.setEnabled(false);
                        jL3_OFF.setText("Switch OFF?");
                }
                
                if (charData3 == '1')  {
                        jL4_TF.setBackground(Color.green);
                        jL4_ON.setEnabled(false);
                        jL4_ON.setText("Switch ON?");
                        jL4_OFF.setEnabled(true);
                        jL4_OFF.setText("Switch OFF?");
                }
                else                     {
                        jL4_TF.setBackground(Color.red);
                        jL4_ON.setEnabled(true);
                        jL4_ON.setText("Switch ON?");
                        jL4_OFF.setEnabled(false);
                        jL4_OFF.setText("Switch OFF?");
                }
                
                if (charData4 == '1')  {
                        jL5_TF.setBackground(Color.green);
                        jL5_ON.setEnabled(false);
                        jL5_ON.setText("Switch ON?");
                        jL5_OFF.setEnabled(true);
                        jL5_OFF.setText("Switch OFF?");
                }
                else                     {
                        jL5_TF.setBackground(Color.red);
                        jL5_ON.setEnabled(true);
                        jL5_ON.setText("Switch ON?");
                        jL5_OFF.setEnabled(false);
                        jL5_OFF.setText("Switch OFF?");
                }
                
                
            }
    }

    catch(IOException | InterruptedException e) {
    }
  
    
   System.gc ();
      }
      catch(Exception e){
        jOffline_TF.setBackground(Color.red);
        jOnline_TF.setBackground(Color.white);
        javax.swing.JOptionPane.showMessageDialog(null,"Please connect to Internet and click 'Auto Refresh' and try again");
        jL1_TF.setBackground(Color.white);
        jL2_TF.setBackground(Color.white);
        jL3_TF.setBackground(Color.white);
        jL4_TF.setBackground(Color.white);
        jL5_TF.setBackground(Color.white);
        jL1_ON.setEnabled(false);
        jL1_OFF.setEnabled(false);
        jL2_ON.setEnabled(false);
        jL2_OFF.setEnabled(false);
        jL3_ON.setEnabled(false);
        jL3_OFF.setEnabled(false);
        jL4_ON.setEnabled(false);
        jL4_OFF.setEnabled(false);
        jL5_ON.setEnabled(false);
        jL5_OFF.setEnabled(false);
        jRefresh.setEnabled(true);        
        break;
      }
     finally{
          try {sock.close ();}
           catch (Exception e) {}
          
      }
  } 
  }
};
refresh.start();
	}//GEN-LAST:event_jRefreshActionPerformed

    private void jL1_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jL1_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jL1_TFActionPerformed

    private void jL1_ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jL1_ONActionPerformed
       try 
                {        
                        java.io.File file = new java.io.File("E:\\iot\\ledblink\\logwrite.txt");                     
                        Scanner input = new Scanner(file);                        
                        while (input.hasNext( ) )
                       {
                                String num = input.nextLine();
                                StringBuilder text = new StringBuilder(num);
                                text.setCharAt(0, '1');
                                PrintStream out = new PrintStream(new FileOutputStream("E:\\iot\\ledblink\\logwrite.txt"));
                                System.setOut(out);
                                System.out.println(text);
                       }                    
                       
                        jL1_ON.setBackground(Color.orange);
                        jL1_ON.setText("Switching ON...");
                        jL1_ON.setEnabled(false);
                        String[] command = {"cmd.exe", "/C", "Start /b  /wait","E:\\iot\\push.bat"};
                        Process p= Runtime.getRuntime().exec(command);
                        int exitVal = p.waitFor();
                        
        } 
       catch(IOException | InterruptedException e) {
        //JOptionPane.showMessageDialog(this, e.getMessage());
        }
    
        System.gc ();
    }//GEN-LAST:event_jL1_ONActionPerformed

    private void jL2_ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jL2_ONActionPerformed
        try 
                {        
                        java.io.File file = new java.io.File("E:\\iot\\ledblink\\logwrite.txt");                     
                        Scanner input = new Scanner(file);                        
                        while (input.hasNext( ) )
                       {
                                String num = input.nextLine();
                                StringBuilder text = new StringBuilder(num);
                                text.setCharAt(1, '1');
                                PrintStream out = new PrintStream(new FileOutputStream("E:\\iot\\ledblink\\logwrite.txt"));
                                System.setOut(out);
                                System.out.println(text);
                       }                    
                        jL2_ON.setBackground(Color.orange);
                        jL2_ON.setText("Switching ON...");
                        jL2_ON.setEnabled(false);
                        String[] command = {"cmd.exe", "/C", "Start /b  /wait","E:\\iot\\push.bat"};
                        Process p= Runtime.getRuntime().exec(command);
                        int exitVal = p.waitFor();
                       
        }  
        catch(IOException | InterruptedException e) {
        //JOptionPane.showMessageDialog(this, e.getMessage());
        }
    
        System.gc ();
    }//GEN-LAST:event_jL2_ONActionPerformed

    private void jL1_OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jL1_OFFActionPerformed
        try 
                {        
                        java.io.File file = new java.io.File("E:\\iot\\ledblink\\logwrite.txt");                     
                        Scanner input = new Scanner(file);                        
                        while (input.hasNext( ) )
                       {
                                String num = input.nextLine();
                                StringBuilder text = new StringBuilder(num);
                                text.setCharAt(0, '0');
                                PrintStream out = new PrintStream(new FileOutputStream("E:\\iot\\ledblink\\logwrite.txt"));
                                System.setOut(out);
                                System.out.println(text);
                       }                    
                        jL1_OFF.setBackground(Color.orange);
                        jL1_OFF.setText("Switching OFF...");
                        jL1_OFF.setEnabled(false);
                        String[] command = {"cmd.exe", "/C", "Start /b  /wait","E:\\iot\\push.bat"};
                        Process p= Runtime.getRuntime().exec(command);
                        int exitVal = p.waitFor();
                        
        }
        catch(IOException | InterruptedException e) {
        //JOptionPane.showMessageDialog(this, e.getMessage());
        }
    
        System.gc ();
    }//GEN-LAST:event_jL1_OFFActionPerformed

    private void jL2_OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jL2_OFFActionPerformed
        try
        {
            java.io.File file = new java.io.File("E:\\iot\\ledblink\\logwrite.txt");
            Scanner input = new Scanner(file);
            while (input.hasNext( ) )
            {
                String num = input.nextLine();
                StringBuilder text = new StringBuilder(num);
                text.setCharAt(1, '0');
                PrintStream out = new PrintStream(new FileOutputStream("E:\\iot\\ledblink\\logwrite.txt"));
                System.setOut(out);
                System.out.println(text);
            }
            jL2_OFF.setBackground(Color.orange);
            jL2_OFF.setText("Switching OFF...");
            jL2_OFF.setEnabled(false);
            String[] command = {"cmd.exe", "/C", "Start /b /wait","E:\\iot\\push.bat"};
            Process p= Runtime.getRuntime().exec(command);
            int exitVal = p.waitFor();

        } 
        catch(IOException | InterruptedException e) {
        //JOptionPane.showMessageDialog(this, e.getMessage());
        }

        System.gc ();
    }//GEN-LAST:event_jL2_OFFActionPerformed

    private void jEXIT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEXIT2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jEXIT2ActionPerformed

    private void jOnline_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOnline_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jOnline_TFActionPerformed

    private void jL2_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jL2_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jL2_TFActionPerformed

    private void jOffline_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOffline_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jOffline_TFActionPerformed

    private void jL3_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jL3_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jL3_TFActionPerformed

    private void jL4_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jL4_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jL4_TFActionPerformed

    private void jL3_ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jL3_ONActionPerformed
        try 
                {        
                        java.io.File file = new java.io.File("E:\\iot\\ledblink\\logwrite.txt");                     
                        Scanner input = new Scanner(file);                        
                        while (input.hasNext( ) )
                       {
                                String num = input.nextLine();
                                StringBuilder text = new StringBuilder(num);
                                text.setCharAt(2, '1');
                                PrintStream out = new PrintStream(new FileOutputStream("E:\\iot\\ledblink\\logwrite.txt"));
                                System.setOut(out);
                                System.out.println(text);
                       }                    
                       
                        jL3_ON.setBackground(Color.orange);
                        jL3_ON.setText("Switching ON...");
                        jL3_ON.setEnabled(false);
                        String[] command = {"cmd.exe", "/C", "Start /b  /wait","E:\\iot\\push.bat"};
                        Process p= Runtime.getRuntime().exec(command);
                        int exitVal = p.waitFor();
                        
        } 
       catch(IOException | InterruptedException e) {
        //JOptionPane.showMessageDialog(this, e.getMessage());
        }
    
        System.gc ();
        // TODO add your handling code here:
    }//GEN-LAST:event_jL3_ONActionPerformed

    private void jL4_ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jL4_ONActionPerformed
        try 
                {        
                        java.io.File file = new java.io.File("E:\\iot\\ledblink\\logwrite.txt");                     
                        Scanner input = new Scanner(file);                        
                        while (input.hasNext( ) )
                       {
                                String num = input.nextLine();
                                StringBuilder text = new StringBuilder(num);
                                text.setCharAt(3, '1');
                                PrintStream out = new PrintStream(new FileOutputStream("E:\\iot\\ledblink\\logwrite.txt"));
                                System.setOut(out);
                                System.out.println(text);
                       }                    
                       
                        jL4_ON.setBackground(Color.orange);
                        jL4_ON.setText("Switching ON...");
                        jL4_ON.setEnabled(false);
                        String[] command = {"cmd.exe", "/C", "Start /b  /wait","E:\\iot\\push.bat"};
                        Process p= Runtime.getRuntime().exec(command);
                        int exitVal = p.waitFor();
                        
        } 
       catch(IOException | InterruptedException e) {
        //JOptionPane.showMessageDialog(this, e.getMessage());
        }
    
        System.gc ();
        // TODO add your handling code here:
    }//GEN-LAST:event_jL4_ONActionPerformed

    private void jL3_OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jL3_OFFActionPerformed
        try 
                {        
                        java.io.File file = new java.io.File("E:\\iot\\ledblink\\logwrite.txt");                     
                        Scanner input = new Scanner(file);                        
                        while (input.hasNext( ) )
                       {
                                String num = input.nextLine();
                                StringBuilder text = new StringBuilder(num);
                                text.setCharAt(2, '0');
                                PrintStream out = new PrintStream(new FileOutputStream("E:\\iot\\ledblink\\logwrite.txt"));
                                System.setOut(out);
                                System.out.println(text);
                       }                    
                        jL3_OFF.setBackground(Color.orange);
                        jL3_OFF.setText("Switching OFF...");
                        jL3_OFF.setEnabled(false);
                        String[] command = {"cmd.exe", "/C", "Start /b  /wait","E:\\iot\\push.bat"};
                        Process p= Runtime.getRuntime().exec(command);
                        int exitVal = p.waitFor();
                        
        }
        catch(IOException | InterruptedException e) {
        //JOptionPane.showMessageDialog(this, e.getMessage());
        }
    
        System.gc ();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jL3_OFFActionPerformed

    private void jL4_OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jL4_OFFActionPerformed
        try 
                {        
                        java.io.File file = new java.io.File("E:\\iot\\ledblink\\logwrite.txt");                     
                        Scanner input = new Scanner(file);                        
                        while (input.hasNext( ) )
                       {
                                String num = input.nextLine();
                                StringBuilder text = new StringBuilder(num);
                                text.setCharAt(3, '0');
                                PrintStream out = new PrintStream(new FileOutputStream("E:\\iot\\ledblink\\logwrite.txt"));
                                System.setOut(out);
                                System.out.println(text);
                       }                    
                        jL4_OFF.setBackground(Color.orange);
                        jL4_OFF.setText("Switching OFF...");
                        jL4_OFF.setEnabled(false);
                        String[] command = {"cmd.exe", "/C", "Start /b  /wait","E:\\iot\\push.bat"};
                        Process p= Runtime.getRuntime().exec(command);
                        int exitVal = p.waitFor();
                        
        }
        catch(IOException | InterruptedException e) {
        //JOptionPane.showMessageDialog(this, e.getMessage());
        }
    
        System.gc ();
        // TODO add your handling code here:
    }//GEN-LAST:event_jL4_OFFActionPerformed

    private void jL5_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jL5_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jL5_TFActionPerformed

    private void jL5_ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jL5_ONActionPerformed
        try 
                {        
                        java.io.File file = new java.io.File("E:\\iot\\ledblink\\logwrite.txt");                     
                        Scanner input = new Scanner(file);                        
                        while (input.hasNext( ) )
                       {
                                String num = input.nextLine();
                                StringBuilder text = new StringBuilder(num);
                                text.setCharAt(4, '1');
                                PrintStream out = new PrintStream(new FileOutputStream("E:\\iot\\ledblink\\logwrite.txt"));
                                System.setOut(out);
                                System.out.println(text);
                       }                    
                       
                        jL5_ON.setBackground(Color.orange);
                        jL5_ON.setText("Switching ON...");
                        jL5_ON.setEnabled(false);
                        String[] command = {"cmd.exe", "/C", "Start /b  /wait","E:\\iot\\push.bat"};
                        Process p= Runtime.getRuntime().exec(command);
                        int exitVal = p.waitFor();
                        
        } 
       catch(IOException | InterruptedException e) {
        //JOptionPane.showMessageDialog(this, e.getMessage());
        }
    
        System.gc ();
        // TODO add your handling code here:
    }//GEN-LAST:event_jL5_ONActionPerformed

    private void jL5_OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jL5_OFFActionPerformed
        try 
                {        
                        java.io.File file = new java.io.File("E:\\iot\\ledblink\\logwrite.txt");                     
                        Scanner input = new Scanner(file);                        
                        while (input.hasNext( ) )
                       {
                                String num = input.nextLine();
                                StringBuilder text = new StringBuilder(num);
                                text.setCharAt(4, '0');
                                PrintStream out = new PrintStream(new FileOutputStream("E:\\iot\\ledblink\\logwrite.txt"));
                                System.setOut(out);
                                System.out.println(text);
                       }                    
                        jL5_OFF.setBackground(Color.orange);
                        jL5_OFF.setText("Switching OFF...");
                        jL5_OFF.setEnabled(false);
                        String[] command = {"cmd.exe", "/C", "Start /b  /wait","E:\\iot\\push.bat"};
                        Process p= Runtime.getRuntime().exec(command);
                        int exitVal = p.waitFor();
                        
        }
        catch(IOException | InterruptedException e) {
        //JOptionPane.showMessageDialog(this, e.getMessage());
        }
    
        System.gc ();
        // TODO add your handling code here:
    }//GEN-LAST:event_jL5_OFFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jClear1_BT;
    private javax.swing.JButton jEXIT1_BT;
    private javax.swing.JButton jEXIT2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JButton jL1_OFF;
    private javax.swing.JButton jL1_ON;
    private javax.swing.JTextField jL1_TF;
    private javax.swing.JLabel jL1_label;
    private javax.swing.JButton jL2_OFF;
    private javax.swing.JButton jL2_ON;
    private javax.swing.JTextField jL2_TF;
    private javax.swing.JLabel jL2_label;
    private javax.swing.JButton jL3_OFF;
    private javax.swing.JButton jL3_ON;
    private javax.swing.JTextField jL3_TF;
    private javax.swing.JLabel jL3_label;
    private javax.swing.JButton jL4_OFF;
    private javax.swing.JButton jL4_ON;
    private javax.swing.JTextField jL4_TF;
    private javax.swing.JLabel jL4_label;
    private javax.swing.JLabel jL5_LB;
    private javax.swing.JButton jL5_OFF;
    private javax.swing.JButton jL5_ON;
    private javax.swing.JTextField jL5_TF;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLoginForm_LB;
    private javax.swing.JButton jLogin_BT;
    private javax.swing.JLabel jOffline_LB;
    private javax.swing.JTextField jOffline_TF;
    private javax.swing.JLabel jOnline_LB;
    private javax.swing.JTextField jOnline_TF;
    private javax.swing.JLabel jPwd_LB;
    private javax.swing.JPasswordField jPwd_PF;
    private javax.swing.JButton jRefresh;
    private javax.swing.JLabel jStatus_LB;
    private javax.swing.JLabel jUN_LB;
    private javax.swing.JTextField jUsn_TF;
    // End of variables declaration//GEN-END:variables
}
